"""sect

Revision ID: 9696f7233fb7
Revises: fad76d60b0a9
Create Date: 2023-07-24 19:29:42.922140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9696f7233fb7'
down_revision = 'fad76d60b0a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_assigned_to', table_name='tasks')
    op.drop_constraint('tasks_assigned_to_fkey', 'tasks', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('tasks_assigned_to_fkey', 'tasks', 'managers', ['assigned_to'], ['id'])
    op.create_index('ix_tasks_assigned_to', 'tasks', ['assigned_to'], unique=False)
    # ### end Alembic commands ###
